### ISSUE TITLE
Amélioration côté  fonctionnement

### ISSUE THREAD

**Issue by gaetan1903** [iTeam-S/Stat-Membre#5]
Rehefa avy any amn Top 5, de mande ao amn membre, donc tokony avec le rang zany affichage

1. Possible de faire order point_experience ve zany ty page ty ? 

![image](https://user-images.githubusercontent.com/43904633/157378233-fd8f699f-40d4-486e-9660-35fad1cd4ac7.png)
 
2. ilay Menu ajouter projet ve possible hoe efa misy compte connecter vo miseo ? 

![image](https://user-images.githubusercontent.com/43904633/157378465-676c659e-b7a0-4a68-b7e2-f9eacc59f79a.png)

**Comment by hasina821** [comment]
oui possible daholo izy roa reo,,,,tena zao vo tsikaritro fa sorry,,ataoko zao

**Comment by amada10** [comment]
deuxième done.

**Comment by gaetan1903** [comment]
Je verifie, je valide après

**Comment by gaetan1903** [comment]
@hasina821  @amada10 c'est bon, 

on peut clôturer
